# Generated by Django 5.1.4 on 2024-12-22 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('height', models.CharField(max_length=10)),
                ('weight', models.IntegerField()),
                ('position', models.CharField(max_length=20)),
                ('batting_hand', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('S', 'Switch')], max_length=1)),
                ('throwing_hand', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=1)),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='player_headshots/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('media', models.FileField(blank=True, null=True, upload_to='tutorials/')),
            ],
        ),
        migrations.CreateModel(
            name='AtBat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField()),
                ('result', models.CharField(max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('batter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batter_atbats', to='api.playerbio')),
                ('pitcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitcher_atbats', to='api.playerbio')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAdvancedStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wOBA', models.FloatField()),
                ('wRC_plus', models.FloatField()),
                ('xBA', models.FloatField()),
                ('xSLG', models.FloatField()),
                ('xWOBA', models.FloatField()),
                ('fWAR', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playerbio')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerFieldingAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fielding', models.IntegerField()),
                ('arm_strength', models.IntegerField()),
                ('arm_accuracy', models.IntegerField()),
                ('reaction', models.IntegerField()),
                ('blocking', models.IntegerField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.playerbio')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerHittingAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_left', models.IntegerField()),
                ('contact_right', models.IntegerField()),
                ('power_left', models.IntegerField()),
                ('power_right', models.IntegerField()),
                ('plate_vision', models.IntegerField()),
                ('plate_discipline', models.IntegerField()),
                ('batting_clutch', models.IntegerField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.playerbio')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPitchingAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamina', models.IntegerField()),
                ('hits_per_9', models.IntegerField()),
                ('k_per_9', models.IntegerField()),
                ('bb_per_9', models.IntegerField()),
                ('hr_per_9', models.IntegerField()),
                ('pitching_clutch', models.IntegerField()),
                ('control', models.IntegerField()),
                ('velocity', models.IntegerField()),
                ('break_attr', models.IntegerField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.playerbio')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPitchTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_name', models.CharField(max_length=50)),
                ('velocity', models.IntegerField()),
                ('control', models.IntegerField()),
                ('break_attr', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playerbio')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPitchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_rate', models.FloatField()),
                ('effectiveness_rating', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playerbio')),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playerpitchtypes')),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocity', models.IntegerField()),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('outcome', models.CharField(max_length=50)),
                ('at_bat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.atbat')),
                ('pitch_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playerpitchtypes')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField()),
                ('highlight_video', models.FileField(blank=True, null=True, upload_to='player_videos/')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playerbio')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRunningAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField()),
                ('stealing', models.IntegerField()),
                ('baserunning_aggressiveness', models.IntegerField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.playerbio')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scouting_report', models.TextField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playerbio')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField(default=0)),
                ('at_bats', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('doubles', models.IntegerField(default=0)),
                ('triples', models.IntegerField(default=0)),
                ('home_runs', models.IntegerField(default=0)),
                ('rbi', models.IntegerField(default=0)),
                ('walks', models.IntegerField(default=0)),
                ('strikeouts', models.IntegerField(default=0)),
                ('stolen_bases', models.IntegerField(default=0)),
                ('caught_stealing', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playerbio')),
            ],
        ),
        migrations.AddField(
            model_name='playerbio',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='api.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='api.team'),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='coach_headshots/')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField()),
                ('highlight_video', models.FileField(blank=True, null=True, upload_to='team_videos/')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamScouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scouting_report', models.TextField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='UserAdvancedStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_score', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
